name: wathef
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.6.1

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.4.0
  retrofit: ^4.4.2
  json_annotation: ^4.9.0
  flutter_bloc: ^9.1.0
  equatable: ^2.0.5
  just_audio: ^0.9.36
  audio_service: ^0.18.12
  go_router: ^15.0.0
  cached_network_image: ^3.3.1
  get_it: ^8.0.3
  logger: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.15
  retrofit_generator: ^9.1.9
  json_serializable: ^6.9.4
  flutter_lints: ^5.0.0
dependency_overrides:
  analyzer: ^6.4.1
flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/